
select *
from churn_predictions;

select *
from customer_rfm;

SELECT 
    r.C_CUSTKEY,
    r.RECENCY_SCORE,
    r.FREQUENCY_SCORE,
    r.MONETARY_SCORE,
    r.RFM_SEGMENT,
    c.AVG_ORDER_VALUE,
    c.CHURNED,
    c.RETURN_RATE,
    c.PREDICTED_CHURN
FROM V_CUSTOMER_RFM r
JOIN CHURN_PREDICTIONS c ON r.C_CUSTKEY = c.C_CUSTKEY;

SHOW PRIMARY KEYS IN DATABASE;CREATE OR REPLACE TEMPORARY TABLE PK as SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));SHOW IMPORTED KEYS IN DATABASE;CREATE OR REPLACE TEMPORARY TABLE FK as SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));SHOW UNIQUE KEYS IN DATABASE;CREATE OR REPLACE TEMPORARY TABLE UK as SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));SELECT 'snowflake' AS dbms,c.TABLE_CATALOG,c.TABLE_SCHEMA,c.TABLE_NAME,c.COLUMN_NAME,c.ORDINAL_POSITION,CASE WHEN c.DATA_TYPE ILIKE 'NUMBER' THEN 'NUMBER(' || c.NUMERIC_PRECISION || ',' || c.NUMERIC_SCALE || ')' ELSE UPPER(c.DATA_TYPE)END AS DATA_TYPE,c.CHARACTER_MAXIMUM_LENGTH,LISTAGG(DISTINCT CASE WHEN pk."column_name" IS NOT NULL THEN 'PRIMARY KEY' WHEN fk."fk_column_name" IS NOT NULL THEN 'FOREIGN KEY' WHEN uk."column_name" IS NOT NULL THEN 'UNIQUE' ELSE NULL END,',')WITHIN GROUP(ORDER BY 1)AS CONSTRAINT_TYPE,fk."pk_schema_name" AS REFERENCED_TABLE_SCHEMA,fk."pk_table_name" AS REFERENCED_TABLE_NAME,fk."pk_column_name" AS REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS c LEFT JOIN pk ON c.TABLE_CATALOG=pk."database_name" AND c.TABLE_SCHEMA=pk."schema_name" AND c.TABLE_NAME=pk."table_name" AND c.COLUMN_NAME=pk."column_name" LEFT JOIN uk ON c.TABLE_CATALOG=uk."database_name" AND c.TABLE_SCHEMA=uk."schema_name" AND c.TABLE_NAME=uk."table_name" AND c.COLUMN_NAME=uk."column_name" LEFT JOIN fk ON c.TABLE_CATALOG=fk."fk_database_name" AND c.TABLE_SCHEMA=fk."fk_schema_name" AND c.TABLE_NAME=fk."fk_table_name" AND c.COLUMN_NAME=fk."fk_column_name" WHERE c.TABLE_SCHEMA NOT IN('INFORMATION_SCHEMA','ACCOUNT_USAGE')AND c.TABLE_NAME NOT IN('PK','UK','FK','C')GROUP BY c.TABLE_CATALOG,c.TABLE_SCHEMA,c.TABLE_NAME,c.COLUMN_NAME,c.ORDINAL_POSITION,c.DATA_TYPE,c.NUMERIC_PRECISION,c.NUMERIC_SCALE,c.CHARACTER_MAXIMUM_LENGTH,fk."pk_schema_name",fk."pk_table_name",fk."pk_column_name",REFERENCED_COLUMN_NAME ORDER BY c.TABLE_CATALOG,c.TABLE_SCHEMA,c.TABLE_NAME,c.ORDINAL_POSITION;

