-- ============================================================================
-- DATA DICTIONARY: CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS
-- Profiles each view: Column Name, Description, Sample Values, N, Pct, Min, Max
-- ============================================================================

-- ============================================================================
-- 1. CARGO_TRACKING
-- ============================================================================
WITH base AS (
    SELECT *, COUNT(*) OVER () AS total_rows
    FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.CARGO_TRACKING
),
col_profiles AS (
    SELECT 'IMO' AS column_name, 'Vessel IMO number' AS description,
        NULL AS sample_values,
        COUNT(IMO) AS n, total_rows,
        ROUND(COUNT(IMO)*100.0/NULLIF(total_rows,0),2) AS pct,
        CAST(MIN(IMO) AS VARCHAR) AS min_val,
        CAST(MAX(IMO) AS VARCHAR) AS max_val, 1 AS sort_order
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_NAME', 'Name of the vessel',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_NAME AS val FROM base WHERE VESSEL_NAME IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_NAME), total_rows,
        ROUND(COUNT(VESSEL_NAME)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)', 2
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_CLASS', 'Vessel size classification',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_CLASS AS val FROM base WHERE VESSEL_CLASS IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_CLASS), total_rows,
        ROUND(COUNT(VESSEL_CLASS)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)', 3
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_DATE', 'End date of loading', NULL,
        COUNT(LOAD_DATE), total_rows,
        ROUND(COUNT(LOAD_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LOAD_DATE) AS VARCHAR),
        CAST(MAX(LOAD_DATE) AS VARCHAR), 4
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_AREA', 'Broad geographical area of loading',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_AREA AS val FROM base WHERE LOAD_AREA IS NOT NULL LIMIT 5)),
        COUNT(LOAD_AREA), total_rows,
        ROUND(COUNT(LOAD_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_AREA)) AS VARCHAR) || ' (len)', 5
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_COUNTRY', 'Country of loading',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_COUNTRY AS val FROM base WHERE LOAD_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(LOAD_COUNTRY), total_rows,
        ROUND(COUNT(LOAD_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_COUNTRY)) AS VARCHAR) || ' (len)', 6
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_SUBCOUNTRY_AREA', 'Sub-country level area of origin',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_SUBCOUNTRY_AREA AS val FROM base WHERE LOAD_SUBCOUNTRY_AREA IS NOT NULL LIMIT 5)),
        COUNT(LOAD_SUBCOUNTRY_AREA), total_rows,
        ROUND(COUNT(LOAD_SUBCOUNTRY_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_SUBCOUNTRY_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_SUBCOUNTRY_AREA)) AS VARCHAR) || ' (len)', 7
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_PORT', 'Port of loading',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_PORT AS val FROM base WHERE LOAD_PORT IS NOT NULL LIMIT 5)),
        COUNT(LOAD_PORT), total_rows,
        ROUND(COUNT(LOAD_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_PORT)) AS VARCHAR) || ' (len)', 8
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_STS_INDICATOR', 'Ship-to-Ship indicator during loading', NULL,
        COUNT(LOAD_STS_INDICATOR), total_rows,
        ROUND(COUNT(LOAD_STS_INDICATOR)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LOAD_STS_INDICATOR) AS VARCHAR),
        CAST(MAX(LOAD_STS_INDICATOR) AS VARCHAR), 9
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_STS_IMO', 'Other vessel IMO during STS loading', NULL,
        COUNT(LOAD_STS_IMO), total_rows,
        ROUND(COUNT(LOAD_STS_IMO)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LOAD_STS_IMO) AS VARCHAR),
        CAST(MAX(LOAD_STS_IMO) AS VARCHAR), 10
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_QUANTITY_KT', 'Load quantity in kilotonnes', NULL,
        COUNT(LOAD_QUANTITY_KT), total_rows,
        ROUND(COUNT(LOAD_QUANTITY_KT)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(LOAD_QUANTITY_KT),2) AS VARCHAR),
        CAST(ROUND(MAX(LOAD_QUANTITY_KT),2) AS VARCHAR), 11
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_QUANTITY_KBBL', 'Load quantity in kilobarrels', NULL,
        COUNT(LOAD_QUANTITY_KBBL), total_rows,
        ROUND(COUNT(LOAD_QUANTITY_KBBL)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(LOAD_QUANTITY_KBBL),2) AS VARCHAR),
        CAST(ROUND(MAX(LOAD_QUANTITY_KBBL),2) AS VARCHAR), 12
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'ORIGIN_COUNTRY', 'Country of origin',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT ORIGIN_COUNTRY AS val FROM base WHERE ORIGIN_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(ORIGIN_COUNTRY), total_rows,
        ROUND(COUNT(ORIGIN_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(ORIGIN_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(ORIGIN_COUNTRY)) AS VARCHAR) || ' (len)', 13
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'ORIGIN_COUNTRY_GROUP', 'Country grouping of origin',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT ORIGIN_COUNTRY_GROUP AS val FROM base WHERE ORIGIN_COUNTRY_GROUP IS NOT NULL LIMIT 5)),
        COUNT(ORIGIN_COUNTRY_GROUP), total_rows,
        ROUND(COUNT(ORIGIN_COUNTRY_GROUP)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(ORIGIN_COUNTRY_GROUP)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(ORIGIN_COUNTRY_GROUP)) AS VARCHAR) || ' (len)', 14
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'CARGO_TYPE', 'Product name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT CARGO_TYPE AS val FROM base WHERE CARGO_TYPE IS NOT NULL LIMIT 5)),
        COUNT(CARGO_TYPE), total_rows,
        ROUND(COUNT(CARGO_TYPE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(CARGO_TYPE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(CARGO_TYPE)) AS VARCHAR) || ' (len)', 15
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_DATE', 'End date of discharge', NULL,
        COUNT(DISCHARGE_DATE), total_rows,
        ROUND(COUNT(DISCHARGE_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(DISCHARGE_DATE) AS VARCHAR),
        CAST(MAX(DISCHARGE_DATE) AS VARCHAR), 16
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_AREA', 'Broad geographical area of discharge',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_AREA AS val FROM base WHERE DISCHARGE_AREA IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_AREA), total_rows,
        ROUND(COUNT(DISCHARGE_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_AREA)) AS VARCHAR) || ' (len)', 17
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_COUNTRY', 'Country of discharge',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_COUNTRY AS val FROM base WHERE DISCHARGE_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_COUNTRY), total_rows,
        ROUND(COUNT(DISCHARGE_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)', 18
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_SUBCOUNTRY_AREA', 'Sub-country level area of discharge',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_SUBCOUNTRY_AREA AS val FROM base WHERE DISCHARGE_SUBCOUNTRY_AREA IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_SUBCOUNTRY_AREA), total_rows,
        ROUND(COUNT(DISCHARGE_SUBCOUNTRY_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_SUBCOUNTRY_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_SUBCOUNTRY_AREA)) AS VARCHAR) || ' (len)', 19
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_PORT', 'Port of discharge',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_PORT AS val FROM base WHERE DISCHARGE_PORT IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_PORT), total_rows,
        ROUND(COUNT(DISCHARGE_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_PORT)) AS VARCHAR) || ' (len)', 20
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_STS_INDICATOR', 'Ship-to-Ship indicator during discharge', NULL,
        COUNT(DISCHARGE_STS_INDICATOR), total_rows,
        ROUND(COUNT(DISCHARGE_STS_INDICATOR)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(DISCHARGE_STS_INDICATOR) AS VARCHAR),
        CAST(MAX(DISCHARGE_STS_INDICATOR) AS VARCHAR), 21
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_STS_IMO', 'Other vessel IMO during STS discharge', NULL,
        COUNT(DISCHARGE_STS_IMO), total_rows,
        ROUND(COUNT(DISCHARGE_STS_IMO)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(DISCHARGE_STS_IMO) AS VARCHAR),
        CAST(MAX(DISCHARGE_STS_IMO) AS VARCHAR), 22
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DESTINATION_COUNTRY', 'Country of destination',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DESTINATION_COUNTRY AS val FROM base WHERE DESTINATION_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(DESTINATION_COUNTRY), total_rows,
        ROUND(COUNT(DESTINATION_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DESTINATION_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DESTINATION_COUNTRY)) AS VARCHAR) || ' (len)', 23
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DESTINATION_COUNTRY_GROUP', 'Country grouping of destination',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DESTINATION_COUNTRY_GROUP AS val FROM base WHERE DESTINATION_COUNTRY_GROUP IS NOT NULL LIMIT 5)),
        COUNT(DESTINATION_COUNTRY_GROUP), total_rows,
        ROUND(COUNT(DESTINATION_COUNTRY_GROUP)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DESTINATION_COUNTRY_GROUP)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DESTINATION_COUNTRY_GROUP)) AS VARCHAR) || ' (len)', 24
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'CHARTERER', 'Charterer company name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT CHARTERER AS val FROM base WHERE CHARTERER IS NOT NULL LIMIT 5)),
        COUNT(CHARTERER), total_rows,
        ROUND(COUNT(CHARTERER)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(CHARTERER)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(CHARTERER)) AS VARCHAR) || ' (len)', 25
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'SUPPLIER', 'Supplier company name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT SUPPLIER AS val FROM base WHERE SUPPLIER IS NOT NULL LIMIT 5)),
        COUNT(SUPPLIER), total_rows,
        ROUND(COUNT(SUPPLIER)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(SUPPLIER)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(SUPPLIER)) AS VARCHAR) || ' (len)', 26
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'BUYER', 'Buyer company name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT BUYER AS val FROM base WHERE BUYER IS NOT NULL LIMIT 5)),
        COUNT(BUYER), total_rows,
        ROUND(COUNT(BUYER)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(BUYER)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(BUYER)) AS VARCHAR) || ' (len)', 27
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LAST_UPDATE_DATE', 'Flow last modification date', NULL,
        COUNT(LAST_UPDATE_DATE), total_rows,
        ROUND(COUNT(LAST_UPDATE_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LAST_UPDATE_DATE) AS VARCHAR),
        CAST(MAX(LAST_UPDATE_DATE) AS VARCHAR), 28
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_GEO_ASSET', 'GeoAsset of load',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_GEO_ASSET AS val FROM base WHERE LOAD_GEO_ASSET IS NOT NULL LIMIT 5)),
        COUNT(LOAD_GEO_ASSET), total_rows,
        ROUND(COUNT(LOAD_GEO_ASSET)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_GEO_ASSET)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_GEO_ASSET)) AS VARCHAR) || ' (len)', 29
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_GEO_ASSET', 'GeoAsset of discharge',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_GEO_ASSET AS val FROM base WHERE DISCHARGE_GEO_ASSET IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_GEO_ASSET), total_rows,
        ROUND(COUNT(DISCHARGE_GEO_ASSET)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_GEO_ASSET)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_GEO_ASSET)) AS VARCHAR) || ' (len)', 30
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'CARGO_TYPE_SOURCE', 'Generic cargo source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT CARGO_TYPE_SOURCE AS val FROM base WHERE CARGO_TYPE_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(CARGO_TYPE_SOURCE), total_rows,
        ROUND(COUNT(CARGO_TYPE_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(CARGO_TYPE_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(CARGO_TYPE_SOURCE)) AS VARCHAR) || ' (len)', 31
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'GRADE_NAME', 'Specific cargo name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT GRADE_NAME AS val FROM base WHERE GRADE_NAME IS NOT NULL LIMIT 5)),
        COUNT(GRADE_NAME), total_rows,
        ROUND(COUNT(GRADE_NAME)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(GRADE_NAME)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(GRADE_NAME)) AS VARCHAR) || ' (len)', 32
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'GRADE_SOURCE', 'Specific cargo source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT GRADE_SOURCE AS val FROM base WHERE GRADE_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(GRADE_SOURCE), total_rows,
        ROUND(COUNT(GRADE_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(GRADE_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(GRADE_SOURCE)) AS VARCHAR) || ' (len)', 33
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'SANCTION_ENTITIES', 'Body/Jurisdiction of sanction',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT SANCTION_ENTITIES AS val FROM base WHERE SANCTION_ENTITIES IS NOT NULL LIMIT 5)),
        COUNT(SANCTION_ENTITIES), total_rows,
        ROUND(COUNT(SANCTION_ENTITIES)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(SANCTION_ENTITIES)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(SANCTION_ENTITIES)) AS VARCHAR) || ' (len)', 34
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_STS_ID', 'Unique identifier of load STS operation',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_STS_ID AS val FROM base WHERE LOAD_STS_ID IS NOT NULL LIMIT 5)),
        COUNT(LOAD_STS_ID), total_rows,
        ROUND(COUNT(LOAD_STS_ID)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_STS_ID)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_STS_ID)) AS VARCHAR) || ' (len)', 35
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_STS_ID', 'Unique identifier of discharge STS operation',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_STS_ID AS val FROM base WHERE DISCHARGE_STS_ID IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_STS_ID), total_rows,
        ROUND(COUNT(DISCHARGE_STS_ID)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_STS_ID)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_STS_ID)) AS VARCHAR) || ' (len)', 36
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_GEO_ASSET_SOURCE', 'Load geoasset source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_GEO_ASSET_SOURCE AS val FROM base WHERE LOAD_GEO_ASSET_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(LOAD_GEO_ASSET_SOURCE), total_rows,
        ROUND(COUNT(LOAD_GEO_ASSET_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_GEO_ASSET_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_GEO_ASSET_SOURCE)) AS VARCHAR) || ' (len)', 37
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_PORT_SOURCE', 'Load port source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_PORT_SOURCE AS val FROM base WHERE LOAD_PORT_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(LOAD_PORT_SOURCE), total_rows,
        ROUND(COUNT(LOAD_PORT_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_PORT_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_PORT_SOURCE)) AS VARCHAR) || ' (len)', 38
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_COUNTRY_SOURCE', 'Load country source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_COUNTRY_SOURCE AS val FROM base WHERE LOAD_COUNTRY_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(LOAD_COUNTRY_SOURCE), total_rows,
        ROUND(COUNT(LOAD_COUNTRY_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_COUNTRY_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_COUNTRY_SOURCE)) AS VARCHAR) || ' (len)', 39
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_AREA_SOURCE', 'Load area source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT LOAD_AREA_SOURCE AS val FROM base WHERE LOAD_AREA_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(LOAD_AREA_SOURCE), total_rows,
        ROUND(COUNT(LOAD_AREA_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(LOAD_AREA_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(LOAD_AREA_SOURCE)) AS VARCHAR) || ' (len)', 40
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_GEO_ASSET_SOURCE', 'Discharge geoasset source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_GEO_ASSET_SOURCE AS val FROM base WHERE DISCHARGE_GEO_ASSET_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_GEO_ASSET_SOURCE), total_rows,
        ROUND(COUNT(DISCHARGE_GEO_ASSET_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_GEO_ASSET_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_GEO_ASSET_SOURCE)) AS VARCHAR) || ' (len)', 41
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_PORT_SOURCE', 'Discharge port source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_PORT_SOURCE AS val FROM base WHERE DISCHARGE_PORT_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_PORT_SOURCE), total_rows,
        ROUND(COUNT(DISCHARGE_PORT_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_PORT_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_PORT_SOURCE)) AS VARCHAR) || ' (len)', 42
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_COUNTRY_SOURCE', 'Discharge country source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_COUNTRY_SOURCE AS val FROM base WHERE DISCHARGE_COUNTRY_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_COUNTRY_SOURCE), total_rows,
        ROUND(COUNT(DISCHARGE_COUNTRY_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_COUNTRY_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_COUNTRY_SOURCE)) AS VARCHAR) || ' (len)', 43
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_AREA_SOURCE', 'Discharge area source',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DISCHARGE_AREA_SOURCE AS val FROM base WHERE DISCHARGE_AREA_SOURCE IS NOT NULL LIMIT 5)),
        COUNT(DISCHARGE_AREA_SOURCE), total_rows,
        ROUND(COUNT(DISCHARGE_AREA_SOURCE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DISCHARGE_AREA_SOURCE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DISCHARGE_AREA_SOURCE)) AS VARCHAR) || ' (len)', 44
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VOYAGE_ID', 'Sequential voyage number', NULL,
        COUNT(VOYAGE_ID), total_rows,
        ROUND(COUNT(VOYAGE_ID)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(VOYAGE_ID) AS VARCHAR),
        CAST(MAX(VOYAGE_ID) AS VARCHAR), 45
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'FLOW_ID', 'Unique flow identifier',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT FLOW_ID AS val FROM base WHERE FLOW_ID IS NOT NULL LIMIT 5)),
        COUNT(FLOW_ID), total_rows,
        ROUND(COUNT(FLOW_ID)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(FLOW_ID)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(FLOW_ID)) AS VARCHAR) || ' (len)', 46
    FROM base GROUP BY total_rows
)
SELECT
    column_name AS "Column Name",
    description AS "Description",
    sample_values AS "Values (categorical)",
    n AS "N",
    pct AS "Pct %",
    min_val AS "Min",
    max_val AS "Max"
FROM col_profiles
ORDER BY sort_order;


-- ============================================================================
-- 2. FLOATING_STORAGE
-- ============================================================================
WITH base AS (
    SELECT *, COUNT(*) OVER () AS total_rows
    FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.FLOATING_STORAGE
),
col_profiles AS (
    SELECT 'IMO' AS column_name, 'Vessel IMO number' AS description,
        NULL AS sample_values,
        COUNT(IMO) AS n, total_rows,
        ROUND(COUNT(IMO)*100.0/NULLIF(total_rows,0),2) AS pct,
        CAST(MIN(IMO) AS VARCHAR) AS min_val,
        CAST(MAX(IMO) AS VARCHAR) AS max_val, 1 AS sort_order
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_NAME', 'Vessel name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_NAME AS val FROM base WHERE VESSEL_NAME IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_NAME), total_rows,
        ROUND(COUNT(VESSEL_NAME)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)', 2
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_CLASS', 'Vessel class',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_CLASS AS val FROM base WHERE VESSEL_CLASS IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_CLASS), total_rows,
        ROUND(COUNT(VESSEL_CLASS)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)', 3
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REFERENCE_DATE', 'Monthly reference date', NULL,
        COUNT(REFERENCE_DATE), total_rows,
        ROUND(COUNT(REFERENCE_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(REFERENCE_DATE) AS VARCHAR),
        CAST(MAX(REFERENCE_DATE) AS VARCHAR), 4
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'START_DATE', 'Floating storage start date', NULL,
        COUNT(START_DATE), total_rows,
        ROUND(COUNT(START_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(START_DATE) AS VARCHAR),
        CAST(MAX(START_DATE) AS VARCHAR), 5
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'END_DATE', 'Floating storage end date', NULL,
        COUNT(END_DATE), total_rows,
        ROUND(COUNT(END_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(END_DATE) AS VARCHAR),
        CAST(MAX(END_DATE) AS VARCHAR), 6
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'QUANTITY_KILO_BARRELS', 'Quantity in kilo barrels', NULL,
        COUNT(QUANTITY_KILO_BARRELS), total_rows,
        ROUND(COUNT(QUANTITY_KILO_BARRELS)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(QUANTITY_KILO_BARRELS),2) AS VARCHAR),
        CAST(ROUND(MAX(QUANTITY_KILO_BARRELS),2) AS VARCHAR), 7
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'AREA', 'Geographic area',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT AREA AS val FROM base WHERE AREA IS NOT NULL LIMIT 5)),
        COUNT(AREA), total_rows,
        ROUND(COUNT(AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(AREA)) AS VARCHAR) || ' (len)', 8
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'RUN_DATE', 'Data file creation date', NULL,
        COUNT(RUN_DATE), total_rows,
        ROUND(COUNT(RUN_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(RUN_DATE) AS VARCHAR),
        CAST(MAX(RUN_DATE) AS VARCHAR), 9
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'ORIGIN_COUNTRY', 'Country of origin',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT ORIGIN_COUNTRY AS val FROM base WHERE ORIGIN_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(ORIGIN_COUNTRY), total_rows,
        ROUND(COUNT(ORIGIN_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(ORIGIN_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(ORIGIN_COUNTRY)) AS VARCHAR) || ' (len)', 10
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PRODUCT', 'Product name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PRODUCT AS val FROM base WHERE PRODUCT IS NOT NULL LIMIT 6)),
        COUNT(PRODUCT), total_rows,
        ROUND(COUNT(PRODUCT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PRODUCT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PRODUCT)) AS VARCHAR) || ' (len)', 11
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'QUANTITY_KILO_TONNES', 'Quantity in kilo tonnes', NULL,
        COUNT(QUANTITY_KILO_TONNES), total_rows,
        ROUND(COUNT(QUANTITY_KILO_TONNES)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(QUANTITY_KILO_TONNES),2) AS VARCHAR),
        CAST(ROUND(MAX(QUANTITY_KILO_TONNES),2) AS VARCHAR), 12
    FROM base GROUP BY total_rows
)
SELECT
    column_name AS "Column Name",
    description AS "Description",
    sample_values AS "Values (categorical)",
    n AS "N",
    pct AS "Pct %",
    min_val AS "Min",
    max_val AS "Max"
FROM col_profiles
ORDER BY sort_order;


-- ============================================================================
-- 3. FLOWS_REVISIONS
-- ============================================================================
WITH base AS (
    SELECT *, COUNT(*) OVER () AS total_rows
    FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.FLOWS_REVISIONS
),
col_profiles AS (
    SELECT 'REVISION_DATE' AS column_name, 'Date the revision happened' AS description,
        NULL AS sample_values,
        COUNT(REVISION_DATE) AS n, total_rows,
        ROUND(COUNT(REVISION_DATE)*100.0/NULLIF(total_rows,0),2) AS pct,
        CAST(MIN(REVISION_DATE) AS VARCHAR) AS min_val,
        CAST(MAX(REVISION_DATE) AS VARCHAR) AS max_val, 1 AS sort_order
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISION_STATUS', 'Type of the revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISION_STATUS AS val FROM base WHERE REVISION_STATUS IS NOT NULL LIMIT 5)),
        COUNT(REVISION_STATUS), total_rows,
        ROUND(COUNT(REVISION_STATUS)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISION_STATUS)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISION_STATUS)) AS VARCHAR) || ' (len)', 2
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'IMO', 'Vessel IMO number', NULL,
        COUNT(IMO), total_rows,
        ROUND(COUNT(IMO)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(IMO) AS VARCHAR),
        CAST(MAX(IMO) AS VARCHAR), 3
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_NAME', 'Vessel name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_NAME AS val FROM base WHERE VESSEL_NAME IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_NAME), total_rows,
        ROUND(COUNT(VESSEL_NAME)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_NAME)) AS VARCHAR) || ' (len)', 4
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VESSEL_CLASS', 'Vessel class',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT VESSEL_CLASS AS val FROM base WHERE VESSEL_CLASS IS NOT NULL LIMIT 5)),
        COUNT(VESSEL_CLASS), total_rows,
        ROUND(COUNT(VESSEL_CLASS)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(VESSEL_CLASS)) AS VARCHAR) || ' (len)', 5
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'VOYAGE_ID', 'Voyage number', NULL,
        COUNT(VOYAGE_ID), total_rows,
        ROUND(COUNT(VOYAGE_ID)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(VOYAGE_ID) AS VARCHAR),
        CAST(MAX(VOYAGE_ID) AS VARCHAR), 6
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_DATE', 'End date of loading', NULL,
        COUNT(LOAD_DATE), total_rows,
        ROUND(COUNT(LOAD_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LOAD_DATE) AS VARCHAR),
        CAST(MAX(LOAD_DATE) AS VARCHAR), 7
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DISCHARGE_DATE', 'End date of discharge', NULL,
        COUNT(DISCHARGE_DATE), total_rows,
        ROUND(COUNT(DISCHARGE_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(DISCHARGE_DATE) AS VARCHAR),
        CAST(MAX(DISCHARGE_DATE) AS VARCHAR), 8
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_LOAD_PORT', 'Load port before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_LOAD_PORT AS val FROM base WHERE PREVIOUS_LOAD_PORT IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_LOAD_PORT), total_rows,
        ROUND(COUNT(PREVIOUS_LOAD_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_LOAD_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_LOAD_PORT)) AS VARCHAR) || ' (len)', 9
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_LOAD_PORT', 'Load port after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_LOAD_PORT AS val FROM base WHERE REVISED_LOAD_PORT IS NOT NULL LIMIT 5)),
        COUNT(REVISED_LOAD_PORT), total_rows,
        ROUND(COUNT(REVISED_LOAD_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_LOAD_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_LOAD_PORT)) AS VARCHAR) || ' (len)', 10
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_DISCHARGE_SUEZ_POSITION', 'Discharge Suez position before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_DISCHARGE_SUEZ_POSITION AS val FROM base WHERE PREVIOUS_DISCHARGE_SUEZ_POSITION IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_DISCHARGE_SUEZ_POSITION), total_rows,
        ROUND(COUNT(PREVIOUS_DISCHARGE_SUEZ_POSITION)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_DISCHARGE_SUEZ_POSITION)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_DISCHARGE_SUEZ_POSITION)) AS VARCHAR) || ' (len)', 11
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_DISCHARGE_SUEZ_POSITION', 'Discharge Suez position after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_DISCHARGE_SUEZ_POSITION AS val FROM base WHERE REVISED_DISCHARGE_SUEZ_POSITION IS NOT NULL LIMIT 5)),
        COUNT(REVISED_DISCHARGE_SUEZ_POSITION), total_rows,
        ROUND(COUNT(REVISED_DISCHARGE_SUEZ_POSITION)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_DISCHARGE_SUEZ_POSITION)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_DISCHARGE_SUEZ_POSITION)) AS VARCHAR) || ' (len)', 12
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_DISCHARGE_AREA', 'Discharge area before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_DISCHARGE_AREA AS val FROM base WHERE PREVIOUS_DISCHARGE_AREA IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_DISCHARGE_AREA), total_rows,
        ROUND(COUNT(PREVIOUS_DISCHARGE_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_DISCHARGE_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_DISCHARGE_AREA)) AS VARCHAR) || ' (len)', 13
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_DISCHARGE_AREA', 'Discharge area after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_DISCHARGE_AREA AS val FROM base WHERE REVISED_DISCHARGE_AREA IS NOT NULL LIMIT 5)),
        COUNT(REVISED_DISCHARGE_AREA), total_rows,
        ROUND(COUNT(REVISED_DISCHARGE_AREA)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_DISCHARGE_AREA)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_DISCHARGE_AREA)) AS VARCHAR) || ' (len)', 14
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_DISCHARGE_REGION', 'Discharge region before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_DISCHARGE_REGION AS val FROM base WHERE PREVIOUS_DISCHARGE_REGION IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_DISCHARGE_REGION), total_rows,
        ROUND(COUNT(PREVIOUS_DISCHARGE_REGION)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_DISCHARGE_REGION)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_DISCHARGE_REGION)) AS VARCHAR) || ' (len)', 15
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_DISCHARGE_REGION', 'Discharge region after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_DISCHARGE_REGION AS val FROM base WHERE REVISED_DISCHARGE_REGION IS NOT NULL LIMIT 5)),
        COUNT(REVISED_DISCHARGE_REGION), total_rows,
        ROUND(COUNT(REVISED_DISCHARGE_REGION)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_DISCHARGE_REGION)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_DISCHARGE_REGION)) AS VARCHAR) || ' (len)', 16
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_DISCHARGE_COUNTRY', 'Discharge country before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_DISCHARGE_COUNTRY AS val FROM base WHERE PREVIOUS_DISCHARGE_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_DISCHARGE_COUNTRY), total_rows,
        ROUND(COUNT(PREVIOUS_DISCHARGE_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)', 17
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_DISCHARGE_COUNTRY', 'Discharge country after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_DISCHARGE_COUNTRY AS val FROM base WHERE REVISED_DISCHARGE_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(REVISED_DISCHARGE_COUNTRY), total_rows,
        ROUND(COUNT(REVISED_DISCHARGE_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_DISCHARGE_COUNTRY)) AS VARCHAR) || ' (len)', 18
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_DISCHARGE_PORT', 'Discharge port before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_DISCHARGE_PORT AS val FROM base WHERE PREVIOUS_DISCHARGE_PORT IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_DISCHARGE_PORT), total_rows,
        ROUND(COUNT(PREVIOUS_DISCHARGE_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_DISCHARGE_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_DISCHARGE_PORT)) AS VARCHAR) || ' (len)', 19
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_DISCHARGE_PORT', 'Discharge port after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_DISCHARGE_PORT AS val FROM base WHERE REVISED_DISCHARGE_PORT IS NOT NULL LIMIT 5)),
        COUNT(REVISED_DISCHARGE_PORT), total_rows,
        ROUND(COUNT(REVISED_DISCHARGE_PORT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_DISCHARGE_PORT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_DISCHARGE_PORT)) AS VARCHAR) || ' (len)', 20
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PREVIOUS_CARGO_TYPE', 'Cargo type before revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PREVIOUS_CARGO_TYPE AS val FROM base WHERE PREVIOUS_CARGO_TYPE IS NOT NULL LIMIT 5)),
        COUNT(PREVIOUS_CARGO_TYPE), total_rows,
        ROUND(COUNT(PREVIOUS_CARGO_TYPE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PREVIOUS_CARGO_TYPE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PREVIOUS_CARGO_TYPE)) AS VARCHAR) || ' (len)', 21
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REVISED_CARGO_TYPE', 'Cargo type after revision',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT REVISED_CARGO_TYPE AS val FROM base WHERE REVISED_CARGO_TYPE IS NOT NULL LIMIT 5)),
        COUNT(REVISED_CARGO_TYPE), total_rows,
        ROUND(COUNT(REVISED_CARGO_TYPE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(REVISED_CARGO_TYPE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(REVISED_CARGO_TYPE)) AS VARCHAR) || ' (len)', 22
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_QUANTITY_KBBL', 'Load quantity in kilobarrels', NULL,
        COUNT(LOAD_QUANTITY_KBBL), total_rows,
        ROUND(COUNT(LOAD_QUANTITY_KBBL)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(LOAD_QUANTITY_KBBL),2) AS VARCHAR),
        CAST(ROUND(MAX(LOAD_QUANTITY_KBBL),2) AS VARCHAR), 23
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'LOAD_QUANTITY_KT', 'Load quantity in kilotonnes', NULL,
        COUNT(LOAD_QUANTITY_KT), total_rows,
        ROUND(COUNT(LOAD_QUANTITY_KT)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(LOAD_QUANTITY_KT),2) AS VARCHAR),
        CAST(ROUND(MAX(LOAD_QUANTITY_KT),2) AS VARCHAR), 24
    FROM base GROUP BY total_rows
)
SELECT
    column_name AS "Column Name",
    description AS "Description",
    sample_values AS "Values (categorical)",
    n AS "N",
    pct AS "Pct %",
    min_val AS "Min",
    max_val AS "Max"
FROM col_profiles
ORDER BY sort_order;


-- ============================================================================
-- 4. VESSEL_FLOWS
-- ============================================================================
WITH base AS (
    SELECT *, COUNT(*) OVER () AS total_rows
    FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.VESSEL_FLOWS
),
col_profiles AS (
    SELECT 'ORIGIN_COUNTRY_NAME' AS column_name, 'Country of origin' AS description,
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT ORIGIN_COUNTRY_NAME AS val FROM base WHERE ORIGIN_COUNTRY_NAME IS NOT NULL LIMIT 5)) AS sample_values,
        COUNT(ORIGIN_COUNTRY_NAME) AS n, total_rows,
        ROUND(COUNT(ORIGIN_COUNTRY_NAME)*100.0/NULLIF(total_rows,0),2) AS pct,
        CAST(MIN(LENGTH(ORIGIN_COUNTRY_NAME)) AS VARCHAR) || ' (len)' AS min_val,
        CAST(MAX(LENGTH(ORIGIN_COUNTRY_NAME)) AS VARCHAR) || ' (len)' AS max_val, 1 AS sort_order
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DESTINATION_COUNTRY_NAME', 'Country of destination',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DESTINATION_COUNTRY_NAME AS val FROM base WHERE DESTINATION_COUNTRY_NAME IS NOT NULL LIMIT 5)),
        COUNT(DESTINATION_COUNTRY_NAME), total_rows,
        ROUND(COUNT(DESTINATION_COUNTRY_NAME)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DESTINATION_COUNTRY_NAME)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DESTINATION_COUNTRY_NAME)) AS VARCHAR) || ' (len)', 2
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'GROUPBY_DATE_INDICATOR', 'Exports or Imports indicator',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT GROUPBY_DATE_INDICATOR AS val FROM base WHERE GROUPBY_DATE_INDICATOR IS NOT NULL LIMIT 5)),
        COUNT(GROUPBY_DATE_INDICATOR), total_rows,
        ROUND(COUNT(GROUPBY_DATE_INDICATOR)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(GROUPBY_DATE_INDICATOR)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(GROUPBY_DATE_INDICATOR)) AS VARCHAR) || ' (len)', 3
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'ORIGIN_SUB_COUNTRY', 'Sub-country level area of origin',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT ORIGIN_SUB_COUNTRY AS val FROM base WHERE ORIGIN_SUB_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(ORIGIN_SUB_COUNTRY), total_rows,
        ROUND(COUNT(ORIGIN_SUB_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(ORIGIN_SUB_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(ORIGIN_SUB_COUNTRY)) AS VARCHAR) || ' (len)', 4
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'DESTINATION_SUB_COUNTRY', 'Sub-country level destination area',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT DESTINATION_SUB_COUNTRY AS val FROM base WHERE DESTINATION_SUB_COUNTRY IS NOT NULL LIMIT 5)),
        COUNT(DESTINATION_SUB_COUNTRY), total_rows,
        ROUND(COUNT(DESTINATION_SUB_COUNTRY)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(DESTINATION_SUB_COUNTRY)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(DESTINATION_SUB_COUNTRY)) AS VARCHAR) || ' (len)', 5
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'REFERENCE_DATE', 'Date of reference', NULL,
        COUNT(REFERENCE_DATE), total_rows,
        ROUND(COUNT(REFERENCE_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(REFERENCE_DATE) AS VARCHAR),
        CAST(MAX(REFERENCE_DATE) AS VARCHAR), 6
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PRODUCT', 'Product name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PRODUCT AS val FROM base WHERE PRODUCT IS NOT NULL LIMIT 5)),
        COUNT(PRODUCT), total_rows,
        ROUND(COUNT(PRODUCT)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PRODUCT)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PRODUCT)) AS VARCHAR) || ' (len)', 7
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'PRODUCT_GRADE', 'Specific cargo name',
        (SELECT LISTAGG(DISTINCT val, ', ') WITHIN GROUP (ORDER BY val) FROM (SELECT DISTINCT PRODUCT_GRADE AS val FROM base WHERE PRODUCT_GRADE IS NOT NULL LIMIT 5)),
        COUNT(PRODUCT_GRADE), total_rows,
        ROUND(COUNT(PRODUCT_GRADE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(LENGTH(PRODUCT_GRADE)) AS VARCHAR) || ' (len)',
        CAST(MAX(LENGTH(PRODUCT_GRADE)) AS VARCHAR) || ' (len)', 8
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'QUANTITY_KBD', 'Quantity in kilo barrels per day', NULL,
        COUNT(QUANTITY_KBD), total_rows,
        ROUND(COUNT(QUANTITY_KBD)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(QUANTITY_KBD),2) AS VARCHAR),
        CAST(ROUND(MAX(QUANTITY_KBD),2) AS VARCHAR), 9
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'QUANTITY_KBBL', 'Quantity in kilo barrels', NULL,
        COUNT(QUANTITY_KBBL), total_rows,
        ROUND(COUNT(QUANTITY_KBBL)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(QUANTITY_KBBL),2) AS VARCHAR),
        CAST(ROUND(MAX(QUANTITY_KBBL),2) AS VARCHAR), 10
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'QUANTITY_KT', 'Quantity in kilo tonnes', NULL,
        COUNT(QUANTITY_KT), total_rows,
        ROUND(COUNT(QUANTITY_KT)*100.0/NULLIF(total_rows,0),2),
        CAST(ROUND(MIN(QUANTITY_KT),2) AS VARCHAR),
        CAST(ROUND(MAX(QUANTITY_KT),2) AS VARCHAR), 11
    FROM base GROUP BY total_rows
    UNION ALL
    SELECT 'RUN_DATE', 'Data file creation date', NULL,
        COUNT(RUN_DATE), total_rows,
        ROUND(COUNT(RUN_DATE)*100.0/NULLIF(total_rows,0),2),
        CAST(MIN(RUN_DATE) AS VARCHAR),
        CAST(MAX(RUN_DATE) AS VARCHAR), 12
    FROM base GROUP BY total_rows
)
SELECT
    column_name AS "Column Name",
    description AS "Description",
    sample_values AS "Values (categorical)",
    n AS "N",
    pct AS "Pct %",
    min_val AS "Min",
    max_val AS "Max"
FROM col_profiles
ORDER BY sort_order;
