// Identify Vessels With High STS Count For The Last 6 Months
/*
Understand which vessels are used as lightering ones or maybe participate in sanctioned cargo transfers
*/
SELECT
  LOAD_AREA,
  IMO,
  COUNT(*) AS NUMBER_OF_STS_LOADS,
  SUM(LOAD_QUANTITY_KT) AS TOTAL_STS_LOAD_KT
FROM REFINED_PRODUCTS.CARGO_TRACKING
WHERE LOAD_DATE >= DATEADD('month', -6, CURRENT_DATE())
 AND LOAD_STS_INDICATOR = 1
GROUP BY LOAD_AREA, IMO
ORDER BY NUMBER_OF_STS_LOADS DESC
LIMIT 10;
;

select * from REFINED_PRODUCTS.CARGO_TRACKING;

select * from REFINED_PRODUCTS.floating_storage;

select * from refined_products.FLOWS_REVISIONS;

select * from refined_products.VESSEL_FLOWS;




// Track Imports of Refined Products by County
/*
Drill down to country level to see which countries are importing the most of each refined product
*/
SELECT
  DESTINATION_COUNTRY_NAME,
  ORIGIN_COUNTRY_NAME,
  PRODUCT,
  SUM(QUANTITY_KT) AS TOTAL_KT
FROM REFINED_PRODUCTS.VESSEL_FLOWS
WHERE GROUPBY_DATE_INDICATOR = 'Imports'
  AND REFERENCE_DATE >= '2024-12-01'
  AND DESTINATION_COUNTRY_NAME != ORIGIN_COUNTRY_NAME
GROUP BY DESTINATION_COUNTRY_NAME, ORIGIN_COUNTRY_NAME, PRODUCT
ORDER BY TOTAL_KT DESC
LIMIT 20;
;

// Monitor Revisions in Discharge Country
/*
Monitor changes in discharge country the last 7 days
*/
SELECT
  IMO,
  REVISION_DATE,
  PREVIOUS_DISCHARGE_COUNTRY,
  REVISED_DISCHARGE_COUNTRY
FROM REFINED_PRODUCTS.FLOWS_REVISIONS
WHERE REVISION_STATUS = 'Updated'
  AND PREVIOUS_DISCHARGE_COUNTRY != REVISED_DISCHARGE_COUNTRY
  AND REVISION_DATE >= DATEADD('day', -7, CURRENT_DATE())
GROUP BY IMO, REVISION_DATE, PREVIOUS_DISCHARGE_COUNTRY, REVISED_DISCHARGE_COUNTRY;
;

// Monitor Floating Storage by Product and Area
/*
Track which refined products are being stored afloat and where
*/
SELECT
  PRODUCT,
  AREA,
  SUM(QUANTITY_KILO_BARRELS) AS TOTAL_KBBL
FROM REFINED_PRODUCTS.FLOATING_STORAGE
WHERE REFERENCE_DATE = '2025-12-01'
GROUP BY PRODUCT, AREA
ORDER BY TOTAL_KBBL DESC;





SELECT 
  'snowflake' AS dbms,
  c.TABLE_CATALOG,
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.COLUMN_NAME,
  c.ORDINAL_POSITION,
  CASE 
    WHEN c.DATA_TYPE ILIKE 'NUMBER' 
    THEN 'NUMBER(' || c.NUMERIC_PRECISION || ',' || c.NUMERIC_SCALE || ')' 
    ELSE UPPER(c.DATA_TYPE)
  END AS DATA_TYPE,
  c.CHARACTER_MAXIMUM_LENGTH,
  NULL AS CONSTRAINT_TYPE,
  NULL AS REFERENCED_TABLE_SCHEMA,
  NULL AS REFERENCED_TABLE_NAME,
  NULL AS REFERENCED_COLUMN_NAME
FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.INFORMATION_SCHEMA.COLUMNS c
INNER JOIN CARGO_TRACKING_FOR_REFINED_PRODUCTS.INFORMATION_SCHEMA.VIEWS v
  ON c.TABLE_CATALOG = v.TABLE_CATALOG
  AND c.TABLE_SCHEMA = v.TABLE_SCHEMA
  AND c.TABLE_NAME = v.TABLE_NAME
WHERE c.TABLE_SCHEMA = 'REFINED_PRODUCTS'
  AND c.TABLE_NAME IN (
    'CARGO_TRACKING',
    'FLOATING_STORAGE',
    'FLOWS_REVISIONS',
    'VESSEL_FLOWS'
  )
ORDER BY 
  c.TABLE_CATALOG,
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.ORDINAL_POSITION;

// Sub-Question: What percentage of refined products in floating storage are trapped
// in the Persian Gulf (Arabian Gulf) region vs. globally?
// This helps answer the broader business question by quantifying the share of cargo
// that would be stranded if the Strait of Hormuz were closed.
SELECT
  REFERENCE_DATE,
  SUM(QUANTITY_KILO_BARRELS) AS TOTAL_GLOBAL_KBBL,
  SUM(CASE
        WHEN AREA = 'Arabian Gulf & Rea Sea'
          OR ORIGIN_COUNTRY IN ('Iran', 'Iraq', 'Oman', 'United Arab Emirates')
        THEN QUANTITY_KILO_BARRELS
        ELSE 0
      END) AS PERSIAN_GULF_KBBL,
  ROUND(
    (PERSIAN_GULF_KBBL / NULLIF(TOTAL_GLOBAL_KBBL, 0)) * 100,
    2
  ) AS PCT_STRANDED_IN_GULF
FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.FLOATING_STORAGE
WHERE REFERENCE_DATE = (SELECT MAX(REFERENCE_DATE) FROM CARGO_TRACKING_FOR_REFINED_PRODUCTS.REFINED_PRODUCTS.FLOATING_STORAGE)
GROUP BY REFERENCE_DATE
ORDER BY REFERENCE_DATE DESC;