SELECT 
  'snowflake' AS dbms,
  c.TABLE_CATALOG,
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.COLUMN_NAME,
  c.ORDINAL_POSITION,
  CASE 
    WHEN c.DATA_TYPE ILIKE 'NUMBER' 
    THEN 'NUMBER(' || c.NUMERIC_PRECISION || ',' || c.NUMERIC_SCALE || ')' 
    ELSE UPPER(c.DATA_TYPE)
  END AS DATA_TYPE,
  c.CHARACTER_MAXIMUM_LENGTH,
  NULL AS CONSTRAINT_TYPE,
  NULL AS REFERENCED_TABLE_SCHEMA,
  NULL AS REFERENCED_TABLE_NAME,
  NULL AS REFERENCED_COLUSNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.USPTO_PATENT_RELATIONSHIPSSNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.USPTO_CONTRIBUTOR_INDEXSNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.USPTO_CONTRIBUTOR_INDEXSNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.USPTO_CONTRIBUTOR_INDEXMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS c
INNER JOIN INFORMATION_SCHEMA.VIEWS v
  ON c.TABLE_CATALOG = v.TABLE_CATALOG
  AND c.TABLE_SCHEMA = v.TABLE_SCHEMA
  AND c.TABLE_NAME = v.TABLE_NAME
WHERE c.TABLE_NAME IN (
    'USPTO_CONTRIBUTOR_INDEX',
    'USPTO_PATENT_CONTRIBUTOR_RELATIONSHIPS',
    'USPTO_PATENT_INDEX',
    'USPTO_PATENT_TEXT_ATTRIBUTES',
    'USPTO_PATENT_RELATIONSHIPS'
  )
ORDER BY 
  c.TABLE_CATALOG,
  c.TABLE_SCHEMA,
  c.TABLE_NAME,
  c.ORDINAL_POSITION;